module.exports = [
  `There are a lot of concerns as we know, health being one of them. `,
  `Aged care: what are your plans for focusing on that?`,
  `What are you doing about the increased cost of living?`,
  `Is the $1.6 billion underspend of the NDIS due to maladministration?`,
  `Unemployment is so low, but when will wages start to rise?`,
  `Do you think you can deliver budget surpluses?`,
  `Are you going to guarantee all these measures?`,
  `Is it wise to be spending extra money when there are headwinds facing our economy?`,
  `And what are the factors you’re considering?`,
  `Where is the wages growth going to come from?`,
  `Let's talk about your tax plans.`,
  `Why should voters trust you to do what you say?`,
  `How will you restore faith and trust in the political system?`,
  `Will a 45 per cent emissions reduction target affect the economy?`,
  `How much of a threat is climate change to Australia's future?`,
  `How urgent is the need for action on climate change?`,
  `How much does an electric car cost?`,
  `Do high income earners really deserve $140 billion worth of tax cuts?`,
  `Is the franking policy a retirement tax?`,
  `What do you think of Clive Palmer and his campaign?`,
  `What do you admire about your opponent?`,
  `What do voters most need to know about your opponent?`,
  `What should voters know about you?`,
];
